// <auto-generated />
using System;
using AgentCallTracker.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgentCallTracker.API.Migrations
{
    [DbContext(typeof(CallTraceDbContext))]
    partial class CallTraceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgentCallTracker.Model.AgentCallTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcdId")
                        .HasMaxLength(64);

                    b.Property<string>("AgentId")
                        .HasMaxLength(64);

                    b.Property<Guid>("AgentTraceId");

                    b.Property<DateTime>("CallTraceBeginTime");

                    b.Property<DateTime>("CallTraceEndTime");

                    b.Property<string>("TelephonyEnterpriseId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("AgentCallTrace");
                });
#pragma warning restore 612, 618
        }
    }
}
